[package]
name = "food-openapi-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
food-openapi-rs-macros = { path = "./macros" }
inventory = "0.3"
serde = { version = "1", features = ["derive"] }
utoipa = "5"

# Re-export macros
[package.metadata.docs.rs]
all-features = true
